# Generated by Django 4.1.1 on 2022-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=4)),
                ('phone_type', models.CharField(choices=[('Analógico', 'Analógico'), ('Digital', 'Digital')], default='Digital', max_length=9)),
                ('department', models.CharField(max_length=255)),
                ('sponsor', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'ordering': ['department'],
            },
        ),
    ]
