# Generated by Django 4.1.1 on 2022-10-12 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=4, verbose_name='Número do ramal')),
                ('phone_type', models.CharField(choices=[('Analógico', 'Analógico'), ('Digital', 'Digital')], default='Digital', max_length=9, verbose_name='Tipo do telefone')),
                ('department', models.CharField(max_length=255, verbose_name='Setor')),
                ('sponsor', models.CharField(blank=True, max_length=255, verbose_name='Responsável')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrador em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrador por')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'ordering': ['department'],
            },
        ),
    ]
