# Generated by Django 4.1.1 on 2022-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=4, unique=True, verbose_name='Número do ramal'),
        ),
    ]
